---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    pod-security.kubernetes.io/enforce: privileged
  name: vfio-device-plugin

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vfio-device-plugin
  namespace: vfio-device-plugin
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["security.openshift.io"]
    resourceNames: ["privileged"]
    resources: ["securitycontextconstraints"]
    verbs: ["use"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vfio-device-plugin
  namespace: vfio-device-plugin

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vfio-device-plugin
  namespace: vfio-device-plugin
subjects:
  - kind: ServiceAccount
    name: vfio-device-plugin
    namespace: vfio-device-plugin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vfio-device-plugin

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vfio-device-plugin
  namespace: vfio-device-plugin
spec:
  selector:
    matchLabels:
      name: vfio-device-plugin
  template:
    metadata:
      labels:
        name: vfio-device-plugin
    spec:
      serviceAccountName: vfio-device-plugin
      nodeSelector:
        vfio-device: "true"
      hostNetwork: true
      priorityClassName: system-node-critical
      containers:
        - name: vfio-device-plugin
          image: quay.io/jonkey/vfio-device-plugin:0.1
          securityContext:
            runAsNonRoot: false
            allowPrivilegeEscalation: true
            privileged: true
          volumeMounts:
            - name: device-plugins
              mountPath: /var/lib/kubelet/device-plugins
            - name: dev
              mountPath: /dev
            - name: sys
              mountPath: /sys
            - name: config
              mountPath: /etc/vfio
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "100m"
              memory: "100Mi"
      volumes:
        - name: device-plugins
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: dev
          hostPath:
            path: /dev
        - name: sys
          hostPath:
            path: /sys
        - name: config
          configMap:
            name: vfio-devices

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vfio-devices
  namespace: vfio-device-plugin
data:
  config.yaml: |
    resources:
      - resourceName: ib.net/ib1
        addresses:
          - "0000:cc:00.0#1-7"g
      - resourceName: ib.net/ib2
        addresses:
          - "0000:dc:00.0#1-7"
